# Site settings
title: هفته نامه طراحی وب فارسی
email: info@reyhoun.com
description: "لینک های منتخب هفته برای طراحان و توسعه دهندگان"
rss_desc: "بهترین لینک های طراحی وب فارسی در هفته ای که گذشت"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ui.toread.ir" # the base hostname & protocol for your site
twitter_username: uitoread
github_username:  reyhoun/ui.toread

# Build settings
markdown: kramdown
encoding: utf-8
permalink: /:categories/:title
exclude: ["README.md"]
sass:
    style: :compressed